import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { promisify } from 'node:util';
import { afterEach, test } from 'node:test';

import { CLI_VERSION } from '@/configs/constants.js';
import type { DoctorReport } from '@/core/doctor.types.js';

const execFileAsync = promisify(execFile);
const temporaryDirectories: string[] = [];

function hash(content: string): string {
  return createHash('sha256').update(content).digest('hex');
}

async function createHealthyApp(manifestVersion = CLI_VERSION): Promise<string> {
  const root = await mkdtemp(path.join(os.tmpdir(), 'bink-cli-doctor-'));
  temporaryDirectories.push(root);
  const generated = 'export const api = {};\n';
  await writeFile(
    path.join(root, 'package.json'),
    JSON.stringify(
      {
        name: 'cli-doctor-app',
        packageManager: 'yarn@1.22.22',
        dependencies: { axios: '^1.0.0', 'react-native': '0.86.0' },
      },
      null,
      2,
    ),
  );
  await mkdir(path.join(root, 'src/api'), { recursive: true });
  await writeFile(path.join(root, 'src/api/client.ts'), generated);
  await writeFile(
    path.join(root, '.bink-rn-stack.json'),
    JSON.stringify(
      {
        version: manifestVersion,
        modules: ['axios'],
        files: { 'src/api/client.ts': hash(generated) },
        integrations: {},
      },
      null,
      2,
    ),
  );
  return root;
}

async function runDoctor(root: string, ...options: string[]): Promise<string> {
  const executable = path.join(process.cwd(), 'node_modules/.bin/tsx');
  const { stdout } = await execFileAsync(executable, ['src/cli.ts', 'doctor', root, ...options], {
    cwd: process.cwd(),
  });
  return stdout;
}

void afterEach(async () => {
  await Promise.all(
    temporaryDirectories
      .splice(0)
      .map((directory) => rm(directory, { recursive: true, force: true })),
  );
});

void test('prints a human-readable healthy report', async () => {
  const output = await runDoctor(await createHealthyApp());

  assert.match(output, /Doctor report/u);
  assert.match(output, /✔ Project: Bare React Native project detected\./u);
  assert.match(output, /Summary: 7 passed, 0 warnings, 0 errors/u);
});

void test('prints a structured JSON report', async () => {
  const report = JSON.parse(await runDoctor(await createHealthyApp(), '--json')) as DoctorReport;

  assert.equal(report.healthy, true);
  assert.equal(report.project.name, 'cli-doctor-app');
  assert.deepEqual(report.summary, { passed: 7, warnings: 0, errors: 0 });
});

void test('allows warnings normally and fails them in strict mode', async () => {
  const root = await createHealthyApp('0.0.1');
  const output = await runDoctor(root);
  assert.match(output, /1 warning/u);

  await assert.rejects(runDoctor(root, '--strict'), (error: unknown) => {
    const failure = error as { stdout?: string };
    assert.match(failure.stdout ?? '', /CLI version: Manifest was generated by CLI 0\.0\.1/u);
    return true;
  });
});

void test('fails when doctor finds an error', async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'bink-cli-doctor-missing-'));
  temporaryDirectories.push(root);
  await writeFile(
    path.join(root, 'package.json'),
    JSON.stringify({
      name: 'missing-manifest',
      packageManager: 'yarn@1.22.22',
      dependencies: { 'react-native': '0.86.0' },
    }),
  );

  await assert.rejects(runDoctor(root), (error: unknown) => {
    const failure = error as { stdout?: string };
    assert.match(failure.stdout ?? '', /No \.bink-rn-stack\.json file was found/u);
    return true;
  });
});
